"""empty message

Revision ID: 0f6c21c0ec6a
Revises: dc9c67d26c1e
Create Date: 2022-07-26 11:10:56.968363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6c21c0ec6a'
down_revision = 'dc9c67d26c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_string', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_unique_string'), 'trades', ['unique_string'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'admin')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_trades_unique_string'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('nft')
    # ### end Alembic commands ###
