"""empty message

Revision ID: 3840cfd9bd23
Revises: 
Create Date: 2022-07-29 10:49:50.024225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3840cfd9bd23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('network_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('wallet_provider', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'wallet_provider')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'network_name')
    op.drop_column('user', 'network_id')
    op.drop_column('user', 'account')
    # ### end Alembic commands ###
