"""empty message

Revision ID: 52264ef2a19c
Revises: ff41c51395b6
Create Date: 2022-07-26 13:13:52.366270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52264ef2a19c'
down_revision = 'ff41c51395b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
