"""empty message

Revision ID: 53121d9c0f5f
Revises: e6bac4f97e4f
Create Date: 2022-08-08 10:20:38.751849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53121d9c0f5f'
down_revision = 'e6bac4f97e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signed_maker_data', sa.Text(), nullable=True))
    op.drop_index('ix_trades_unique_string', table_name='trades')
    op.drop_column('trades', 'unique_string')
    op.drop_column('trades', 'eth_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('eth_total', sa.FLOAT(), nullable=True))
    op.add_column('trades', sa.Column('unique_string', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_trades_unique_string', 'trades', ['unique_string'], unique=False)
    op.drop_column('trades', 'signed_maker_data')
    # ### end Alembic commands ###
