"""empty message

Revision ID: 8a05f1026694
Revises: c5adce398b05
Create Date: 2022-08-08 15:51:03.534267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a05f1026694'
down_revision = 'c5adce398b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('client_fake_nft_addr', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('our_fake_nft_addr', sa.String(length=256), nullable=True))
    op.drop_column('trades', 'fake_client_nft_addr')
    op.drop_column('trades', 'our_client_nft_addr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('our_client_nft_addr', sa.VARCHAR(length=256), nullable=True))
    op.add_column('trades', sa.Column('fake_client_nft_addr', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('trades', 'our_fake_nft_addr')
    op.drop_column('trades', 'client_fake_nft_addr')
    # ### end Alembic commands ###
