"""empty message

Revision ID: c5adce398b05
Revises: e1a94698aa89
Create Date: 2022-08-08 15:48:25.733959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5adce398b05'
down_revision = 'e1a94698aa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fake_client_nft_addr', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('our_client_nft_addr', sa.String(length=256), nullable=True))
    op.drop_column('trades', 'fake_client_opensea_link')
    op.drop_column('trades', 'our_client_opensea_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('our_client_opensea_link', sa.VARCHAR(length=256), nullable=True))
    op.add_column('trades', sa.Column('fake_client_opensea_link', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('trades', 'our_client_nft_addr')
    op.drop_column('trades', 'fake_client_nft_addr')
    # ### end Alembic commands ###
