"""empty message

Revision ID: d58a463c9bae
Revises: 53121d9c0f5f
Create Date: 2022-08-08 10:23:43.436851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58a463c9bae'
down_revision = '53121d9c0f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('client_nft_address', sa.String(length=128), nullable=True))
    op.add_column('trades', sa.Column('client_nft_token_id', sa.String(length=128), nullable=True))
    op.add_column('trades', sa.Column('our_nft_token_id', sa.String(length=128), nullable=True))
    op.add_column('trades', sa.Column('our_nft_address', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'our_nft_address')
    op.drop_column('trades', 'our_nft_token_id')
    op.drop_column('trades', 'client_nft_token_id')
    op.drop_column('trades', 'client_nft_address')
    # ### end Alembic commands ###
