"""empty message

Revision ID: e1a94698aa89
Revises: ec601ea10d98
Create Date: 2022-08-08 15:47:06.651517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a94698aa89'
down_revision = 'ec601ea10d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fake_client_opensea_link', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('our_client_opensea_link', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('our_fake_token_id', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('client_fake_token_id', sa.String(length=256), nullable=True))
    op.add_column('trades', sa.Column('eth_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'eth_total')
    op.drop_column('trades', 'client_fake_token_id')
    op.drop_column('trades', 'our_fake_token_id')
    op.drop_column('trades', 'our_client_opensea_link')
    op.drop_column('trades', 'fake_client_opensea_link')
    # ### end Alembic commands ###
