"""empty message

Revision ID: e6bac4f97e4f
Revises: 
Create Date: 2022-08-06 11:36:31.456713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bac4f97e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('account', sa.String(length=128), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('nonce', sa.String(length=128), nullable=True),
    sa.Column('network_name', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('wallet_provider', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('nft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_string', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('client_address', sa.String(length=128), nullable=True),
    sa.Column('our_address', sa.String(length=128), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('our_image_icon', sa.String(length=256), nullable=True),
    sa.Column('our_nft_image', sa.String(length=256), nullable=True),
    sa.Column('client_nft_image', sa.String(length=256), nullable=True),
    sa.Column('our_nft_icon', sa.String(length=256), nullable=True),
    sa.Column('client_nft_icon', sa.String(length=256), nullable=True),
    sa.Column('eth_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_unique_string'), 'trades', ['unique_string'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_unique_string'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('nft')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
