"""empty message

Revision ID: ec601ea10d98
Revises: d58a463c9bae
Create Date: 2022-08-08 13:46:43.152782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec601ea10d98'
down_revision = 'd58a463c9bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('client_nft_name', sa.String(length=128), nullable=True))
    op.add_column('trades', sa.Column('our_nft_name', sa.String(length=128), nullable=True))
    op.drop_column('trades', 'expiry_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('expiry_date', sa.DATETIME(), nullable=True))
    op.drop_column('trades', 'our_nft_name')
    op.drop_column('trades', 'client_nft_name')
    # ### end Alembic commands ###
